th4inquiry/PentaDevs

cpp1st/week01/byongmin/examples/first_lambda.cpp
first lambda example
https://docs.microsoft.com/en-us/cpp/cpp/examples-of-lambda-expressions?view=msvc-170
=> first lambda example

cpp1st/week01/hanju/lambda.md, cpp1st/week01/hanju/lambda1.cpp
My first test program for C++ lambda expression.
=> h's lambda expression test

README.md, cpp1st/README.md, cpp1st/week01/hanju/glambda.cpp, devs/hanju/Prerequisites.md
=> README files updated, generic lambda example

cpp1st/week01/taehwan/LambdaExpression.cpp
Lambda expression examples (2nd)
- Function object
- Lambda capture
=> Lambda expression examples (2nd)

cpp1st/week02/taehwan/README.md, devs/Prerequisites.md
- Update prerequisites.md
- Add README.md
=> Update prerequisites.md and add markdown file for Template

cpp1st/week02/jongsang/ExampleCode/MyArray.h, cpp1st/week02/jongsang/ExampleCode/MyArrayLimited.cpp, cpp1st/week02/jongsang/ExampleCode/MyArrayLimited.h, cpp1st/week02/jongsang/ExampleCode/main.cpp
=> Js template

cpp1st/week02/taehwan/README.md, cpp1st/week02/taehwan/Templates.cpp
1. Add code examples for templates
2. Update README.md to add references
=> Code review: templates (1st)

cpp1st/week03/yongho/03_Reverse_MinMax_Accumulate.cpp, cpp1st/week03/yongho/04_Count_find.cpp, cpp1st/week03/yongho/05_lower_upper_bound.cpp, cpp1st/week03/yongho/06_erase.cpp, cpp1st/week03/yongho/07_permutation_distance.cpp, cpp1st/week03/yongho/08_Array_algorithms.cpp, cpp1st/week03/yongho/09_partition_operations.cpp, cpp1st/week03/yongho/STL.md
Important STL, Array algorithms, partition operation
=> Important STL, Array algorithms, partition operation

cpp1st/week03/taehwan/Containers.cpp, cpp1st/week03/taehwan/ExampleExecutor.cpp, cpp1st/week03/taehwan/README.md, cpp1st/week03/taehwan/STL.cpp
- Update README.md
- Add code for containers
=> Review request: C++ STL

cpp1st/week03/taehwan/Algorithms.cpp, cpp1st/week03/taehwan/Containers.cpp, cpp1st/week03/taehwan/ExampleExecutor.cpp, cpp1st/week03/taehwan/README.md, cpp1st/week03/taehwan/Utilities.cpp
- Add code examples for C++ STL algorithms and utilities
- Rename functions
- Update README.md for C++ STL
=> Review request: C++ STL (2nd)

cpp1st/week03/jongsang/MapTest.cpp, cpp1st/week03/jongsang/MapTest.h, cpp1st/week03/jongsang/Person.cpp, cpp1st/week03/jongsang/Person.h, cpp1st/week03/jongsang/VectorTest.cpp, cpp1st/week03/jongsang/VectorTest.h, cpp1st/week03/jongsang/main.cpp
Example code for vector and map
=> Example code for STL

cpp1st/week03/yongho/10_valarray.cpp, cpp1st/week03/yongho/11_Vector.cpp, cpp1st/week03/yongho/STL.md, cpp1st/week04/yongho/03_RAII.cpp, cpp1st/week04/yongho/04_1_UniqurPtr_Cppreference.cpp, cpp1st/week04/yongho/04_UniquePtr.cpp, cpp1st/week04/yongho/05_1_SharedPtr_cppreference.cpp, cpp1st/week04/yongho/05_SharedPtr.cpp, cpp1st/week04/yongho/06_sharedPtrDeleter.cpp, cpp1st/week04/yongho/07_1_WeakPtr_cppreference.cpp, cpp1st/week04/yongho/07_WeakPtr.cpp, cpp1st/week04/yongho/08_CyclicReference.cpp, cpp1st/week04/yongho/09_Performance.cpp, cpp1st/week04/yongho/10_threadSharesOwnerShipSharedPtr.cpp, cpp1st/week04/yongho/Smart_Pointer.md
=> Smart Pointer sample code

cpp1st/week04/jongsang/IPerson.h, cpp1st/week04/jongsang/Person.cpp, cpp1st/week04/jongsang/Person.h, cpp1st/week04/jongsang/SmartPtrTest.cpp, cpp1st/week04/jongsang/SmartPtrTest.h, cpp1st/week04/jongsang/main.cpp
Smart pointer example code : unique_ptr
=> Smart pointer example code

cpp1st/week04/taehwan/ExampleExecutor.cpp, cpp1st/week04/taehwan/README.md, cpp1st/week04/taehwan/SmartPointer.cpp, cpp1st/week04/taehwan/main.cpp
1. Add code examples for smart pointers
2. Update README.md
=> Review request: smart pointers (1st)

cpp1st/week06/taehwan/README.md
Update README.md for Type Deduction
=> Review request: Type Deduction

cpp1st/week06/jongsang/AutoDeduction.cpp, cpp1st/week06/jongsang/AutoDeduction.h, cpp1st/week06/jongsang/Person.cpp, cpp1st/week06/jongsang/Person.h, cpp1st/week06/jongsang/TemplateDeduction.cpp, cpp1st/week06/jongsang/TemplateDeduction.h, cpp1st/week06/jongsang/main.cpp
Type deduction example code for template and auto
=> Js deduction

cpp1st/week07/jongsang/ConstExprTest.cpp, cpp1st/week07/jongsang/ConstExprTest.h, cpp1st/week07/jongsang/TypeTraitTest.cpp, cpp1st/week07/jongsang/TypeTraitTest.h, cpp1st/week07/jongsang/main.cpp
compile time function example simple source code
=> compile time function examples

cpp1st/week08/jongsang/ExceptionTest.cpp, cpp1st/week08/jongsang/ExceptionTest.h, cpp1st/week08/jongsang/MiniDumpTest.cpp, cpp1st/week08/jongsang/MiniDumpTest.h, cpp1st/week08/jongsang/MyExceptionError.cpp, cpp1st/week08/jongsang/MyExceptionError.h, cpp1st/week08/jongsang/main.cpp
Exception handling example code
=> Exception handling example code

cpp1st/week10/Algorithm.cpp, cpp1st/week10/Algorithms.cpp, cpp1st/week10/ExampleExecutor.cpp, cpp1st/week10/README.md
Update algorithms
- Non-modifying sequence operations
- Modifying sequence operations
- Partitioning operations
- Sorting operations
- Binary Search operations
- Minimum/maximum operations
=> Reivew request: Algorithms

C#/README.md, README.md
1. Update new member & cuurent status
2. Update C# study README file
=> Update README files

C#/README.md
=> Update C# study plan
